services:
  ecomcartservice:
    image: ecomcartservice
    build:
      context: .
      dockerfile: EcomCartService/Dockerfile
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecomcartdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 